use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::{
    csp, rpc,
    session::peer::{PeerMessage, PppNotification, PppRequest, PppResponse},
    DynResult,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Request<T> {
    pub id: String,
    pub method: String,
    pub params: Option<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response<T> {
    pub id: String,
    // unlike LSP-style responses, PPP responses carry their method so they
    // can be decoded without correlating against the originating request
    pub method: String,
    pub result: Option<T>,
    // pub error: (),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Notification<T> {
    pub method: String,
    pub params: Option<T>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitializeRequest {
    pub process_id: Option<i32>,
    pub client_info: Option<ClientInfo>,
    pub root_path: Option<String>,
    // #[serde(rename = "initializeOptions")]
    // initialize_options: Option<InitializeOptions>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientInfo {
    pub name: String,
    pub version: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitializeResponse {
    pub host_info: Option<HostInfo>,
    // client id generated by the host.
    // used to identify the client in subsequent messages
    pub client_id: String,
    pub project_dir_name: PathBuf,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HostInfo {
    pub name: String,
    pub version: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitializedNotification {
    pub client_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShutdownRequest;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShutdownResponse;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CursorMovedNotification {
    pub client_id: String,
    pub location: DocumentLocation,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentLocation {
    pub uri: PathBuf,
    pub pos: DocumentPosition,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentPosition {
    pub line: u32,
    pub column: u32,
}

impl From<csp::DocumentLocation> for DocumentLocation {
    fn from(location: csp::DocumentLocation) -> Self {
        Self {
            uri: location.uri,
            pos: location.pos.into(),
        }
    }
}

impl From<csp::DocumentPosition> for DocumentPosition {
    fn from(pos: csp::DocumentPosition) -> Self {
        Self {
            line: pos.line,
            column: pos.column,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentEditModeNotification {
    pub client_id: String,
    pub mode: DocumentEditMode,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentEditFullNotification {
    pub client_id: String,
    pub mode: DocumentEditMode,
    pub uri: PathBuf,
    pub content: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DocumentEditIncrementalNotification {
    pub client_id: String,
    pub mode: DocumentEditMode,
    pub uri: PathBuf,
    pub start: DocumentPosition,
    pub end: DocumentPosition,
    pub content: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum DocumentEditMode {
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "incremental")]
    Incremental,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DirectoriesUploadNotification {
    pub client_id: String,
    pub directories: Vec<Directory>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Directory {
    pub uri: PathBuf,
    #[serde(rename = "type")]
    pub type_: DirectoryType,
    pub content: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum DirectoryType {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "directory")]
    Directory,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct InitialFileNotification {
    pub uri: PathBuf,
}

/// The PPP wire vocabulary: every method name that can appear in a frame,
/// defined once. The codec below and PeerMessage::method() both read from
/// here, so a message always reports exactly the method it travels under.
pub mod method {
    pub const INITIALIZE: &str = "initialize";
    pub const INITIALIZED: &str = "initialized";
    pub const DIRECTORIES_UPLOAD: &str = "directories/upload";
    pub const INITIAL_FILE_URI: &str = "initial_file_uri";
    pub const CURSOR_MOVED: &str = "cursor_moved";
    pub const DOCUMENT_EDIT: &str = "document/edit";
}

// ─── wire codec ──────────────────────────────────────────────────────────
// The link tasks in `net` are the only callers: they decode every frame read
// from the wire into a typed PeerMessage before it reaches the session, and
// encode every PeerMessage the session emits.

pub async fn decode(data: &[u8]) -> DynResult<PeerMessage> {
    let info = rpc::decode_message(data).await?;

    let is_response = serde_json::from_slice::<serde_json::Value>(&info.content)
        .ok()
        .map(|value| value.get("result").is_some())
        .unwrap_or(false);

    match (info.id, info.method, is_response) {
        (Some(req_id), Some(name), true) => {
            let response = match name.as_str() {
                method::INITIALIZE => PppResponse::Initialize(rpc::decode_result(&info.content)?),
                other => return Err(format!("unknown response method: {}", other).into()),
            };

            Ok(PeerMessage::Response { req_id, response })
        }
        (Some(req_id), Some(name), false) => {
            let request = match name.as_str() {
                method::INITIALIZE => PppRequest::Initialize(rpc::decode_params(&info.content)?),
                other => return Err(format!("unknown request method: {}", other).into()),
            };

            Ok(PeerMessage::Request { req_id, request })
        }
        (None, Some(name), _) => Ok(PeerMessage::Notification(decode_notification(
            &name,
            &info.content,
        )?)),
        _ => Err("a message must carry a method".into()),
    }
}

fn decode_notification(name: &str, content: &[u8]) -> DynResult<PppNotification> {
    match name {
        method::INITIALIZED => Ok(PppNotification::Initialized(rpc::decode_params(content)?)),
        method::DIRECTORIES_UPLOAD => Ok(PppNotification::DirectoriesUpload(rpc::decode_params(
            content,
        )?)),
        method::INITIAL_FILE_URI => Ok(PppNotification::InitialFileUri(rpc::decode_params(
            content,
        )?)),
        method::CURSOR_MOVED => Ok(PppNotification::CursorMoved(rpc::decode_params(content)?)),
        method::DOCUMENT_EDIT => {
            let mode: DocumentEditModeNotification = rpc::decode_params(content)?;

            match mode.mode {
                DocumentEditMode::Full => Ok(PppNotification::DocumentEditFull(
                    rpc::decode_params(content)?,
                )),
                DocumentEditMode::Incremental => {
                    todo!("incremental edits not implemented yet")
                }
            }
        }
        other => Err(format!("unknown notification method: {}", other).into()),
    }
}

pub fn encode(message: &PeerMessage) -> DynResult<Vec<u8>> {
    let method = message.method().to_string();

    match message {
        PeerMessage::Request { req_id, request } => match request {
            PppRequest::Initialize(params) => rpc::encode(Request {
                id: req_id.clone(),
                method,
                params: Some(params.clone()),
            }),
        },
        PeerMessage::Response { req_id, response } => match response {
            PppResponse::Initialize(result) => rpc::encode(Response {
                id: req_id.clone(),
                method,
                result: Some(result.clone()),
            }),
        },
        PeerMessage::Notification(notification) => match notification {
            PppNotification::Initialized(params) => rpc::encode(Notification {
                method,
                params: Some(params.clone()),
            }),
            PppNotification::DirectoriesUpload(params) => rpc::encode(Notification {
                method,
                params: Some(params.clone()),
            }),
            PppNotification::InitialFileUri(params) => rpc::encode(Notification {
                method,
                params: Some(params.clone()),
            }),
            PppNotification::CursorMoved(params) => rpc::encode(Notification {
                method,
                params: Some(params.clone()),
            }),
            PppNotification::DocumentEditFull(params) => rpc::encode(Notification {
                method,
                params: Some(params.clone()),
            }),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn notification_roundtrip() {
        let original = PeerMessage::Notification(PppNotification::CursorMoved(
            CursorMovedNotification {
                client_id: "2".into(),
                location: DocumentLocation {
                    uri: PathBuf::from("src/main.rs"),
                    pos: DocumentPosition { line: 4, column: 7 },
                },
            },
        ));

        let decoded = decode(&encode(&original).unwrap()).await.unwrap();

        match decoded {
            PeerMessage::Notification(PppNotification::CursorMoved(params)) => {
                assert_eq!(params.client_id, "2");
                assert_eq!(params.location.pos.line, 4);
                assert_eq!(params.location.pos.column, 7);
            }
            other => panic!("expected a cursor move, got {:?}", other),
        }
    }

    #[tokio::test]
    async fn response_roundtrip() {
        let original = PeerMessage::Response {
            req_id: "42".into(),
            response: PppResponse::Initialize(InitializeResponse {
                host_info: None,
                client_id: "3".into(),
                project_dir_name: PathBuf::from("graffiti-rs"),
            }),
        };

        let decoded = decode(&encode(&original).unwrap()).await.unwrap();

        match decoded {
            PeerMessage::Response {
                req_id,
                response: PppResponse::Initialize(result),
            } => {
                assert_eq!(req_id, "42");
                assert_eq!(result.client_id, "3");
                assert_eq!(result.project_dir_name, PathBuf::from("graffiti-rs"));
            }
            other => panic!("expected an initialize response, got {:?}", other),
        }
    }
}
